version: '3.8'

services:
  api:
    build: 
      context: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0.40-debian
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: DemoAPI
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge