version: '3.8'

services:
  api:
    build: 
      context: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0.40-debian
    ports:
      - "3366:3306" 
    environment:
      MYSQL_USER: dev                    
      MYSQL_PASSWORD: 123abc@A 
      MYSQL_DATABASE: project_demo 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
