version: '3.8'

services:
  api:
    build: 
      context: .
    image: mnhduc/loginproject
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0.40-debian
    environment:
      MYSQL_DATABASE: project_demo
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123abc@A
    ports:
      - "3366:3366" 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
