services:
  # Dịch vụ cho database
  db:
    image: mysql:8.0.38-debian        # Cập nhật theo version MySQL bạn muốn
    environment:
      MYSQL_ROOT_PASSWORD: 123  # Mật khẩu cho user root
      MYSQL_DATABASE: project_demo_lamnv  # Tên cơ sở dữ liệu
    ports:
      - "3366:3306"          # Mở cổng cho MySQL
    volumes:
      - db_data:/var/lib/mysql  # Để lưu trữ dữ liệu giữa các lần khởi động lại container
    networks:
      - mynetwork

  # Dịch vụ cho ứng dụng
  app:
    build: D:\.Net Project\PROJECT_DEMO2  # Đường dẫn đến thư mục chứa mã nguồn của bạn
    ports:
      - "8080:8080"             # Mở cổng cho ứng dụng của bạn (everyport)
    environment:
      DB_HOST: db              # Tên service database trong Docker Compose
      DB_PORT: 3366            # Cổng MySQL
      DB_NAME: project_demo_lamnv  # Tên cơ sở dữ liệu
      DB_USER: dev             # Tên user để kết nối với database
      DB_PASSWORD: 123abc@A  # Mật khẩu cho user
    depends_on:

      - db
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:  # Định nghĩa mạng "mynetwork"
    driver: bridge